### ISSUE TITLE
usage example

### ISSUE THREAD

**Issue by rubenmoor** [george-steel/servant-oauth-server#1]
Can you point me to an example that uses this library?

**Comment by george-steel** [comment]
Unfortunately, this is currently unfinished. It was split out of a proprietary system and is not quite ready for general use. The part for resource servers is the only complete part.

**Comment by rubenmoor** [comment]
Thanks for your quick reply. From what I see, there isn't a straightforward way to implement the oauth2 protocol with servant. This project was the closest thing I could find. Maybe I need some sort of guide rather than a library to get started by myself.

**Comment by george-steel** [comment]
Unfortunately the protocol is quite complex and badly documented. What part of it (i.e. use case) are you trying to use?

**Comment by rubenmoor** [comment]
In the end I'll have a conventional website with admin access and member area.

The user should have the option to authenticate via password (w/o email even). In this case, my server would be the identity provider and i could build something fairly quickly just with servant's basic auth, probably using stateless JWT.

However, I would like to allow for any user to optionally use their facebook, github, google, ... identity to log in, as mere convenienve. This is why I want to work with oauth2.

**Comment by george-steel** [comment]
Ah, the most common and least-documented use case. That is exactly what I was trying to write. The main idea is that that your resource endpoints require a JWT, and your token endpoint takes an assertion (password or a token from an identity provider) and gives you a local token (or possible a JWT and long-lived opaque token pair). Conceptually, it looks like

```
-- Resource server
AuthRequired claims :> Endpoint

-- Token endpoint
"token" :> Post Assertions (Either AuthError (Token claims))
```
